### ISSUE TITLE
ABR support for DASH

### ISSUE THREAD

**Issue by czhou26** [OpenVisualCloud/CDN-Transcode-Sample#10]

**Comment by TangZhiZhen** [comment]
the transcode already used abr ratecontrol on VOD

**Comment by TangZhiZhen** [comment]
Refer to https://github.com/ut0mt8/nginx-rtmp-module/.
Add the possibility to make adaptative streaming (show below configuration, using ffmpeg to trancode in 3 variants, and produce one manifest). note the "max" flag which indicate which representation should have max witdh and height and so use it to create the variant manifest. you can also use any encoder to directly push the variant.
example as follows:
  rtmp {
    server {
    listen 1935;
   
    application test {
      live on;
      exec /usr/bin/ffmpeg -i rtmp://localhost/$app/$name \
       -an -c:v libsvt_hevc -s 854x480 -b:v 2048K -bufsize 2048k -f flv rtmp://localhost/dash/$name_low  \
       -an -c:v libsvt_hevc -s 1280x720 -b:v 4096K -bufsize 4096k -f flv rtmp://localhost/dash/$name_mid  \ 
       -an -c:v libsvt_hevc -s 1920x1080 -b:v 8192K -bufsize 8192k -f flv rtmp://localhost/dash/$name_hi
    }
      
    application dash {
      live on;
      dash on;
      dash_nested on; 
      dash_repetition on;
      dash_path /dev/shm/dash;
      dash_fragment 4; # 4 second is generaly a good choice for live
      dash_playlist_length 120; # keep 120s of tail
      dash_cleanup on;
      dash_variant _low bandwidth="2048000" width="854" height="480";
      dash_variant _med bandwidth="4096000" width="1280" height="720";
      dash_variant _hi bandwidth="8192000" width="1920" height="1080" max;
    }
  }

**Comment by TangZhiZhen** [comment]
https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/26

**Comment by TangZhiZhen** [comment]
ABR support for DASH code is merged and close this issue.
