### ISSUE TITLE
[Bug]Live video play with libsvt_av1 hd2k would stuck sometimes and cannot recover

### ISSUE THREAD

**Issue by chuan12x** [OpenVisualCloud/CDN-Transcode-Sample#109]
test information:
1.cdn version: 4.0
2.allocation test, ffmpeg command:
 ffmpeg -re -stream_loop -1 -i /var/www/archive/bbb_sunflower_1080p_30fps_normal.mp4
          -vf scale=2560:1440 -c:v libsvt_hevc -b:v 10M -g 32 -forced-idr 1 -thread_count
          96 -an -f flv rtmp://cdn-service/dash/aaa_0_0
          -vf scale=2560:1440 -c:v libsvt_av1  -b:v 10M -g 32 -forced-idr 1 -thread_count
          96 -an -f flv rtmp://cdn-service/dash/bbb_0_1
          -abr_pipeline
3.the live pod is alive and the cache files add normally.
4.cpu request:32794.0m, memory request:12746.0Mi
5.reopen the url in vlc, the video can paly normally.
6.the phenomenon can be repeated many times.
7.stuck live: av1-2k-dash
8.sometimes the transcode process would be reset

**Comment by wenquan-mao** [comment]
50% reproduce rate

**Comment by wenquan-mao** [comment]
av1 hd2k known limitation, close bug
