### ISSUE TITLE
ABR support for HLS

### ISSUE THREAD

**Issue by czhou26** [OpenVisualCloud/CDN-Transcode-Sample#11]

**Comment by TangZhiZhen** [comment]
the transcode already used abr ratecontrol on VOD

**Comment by czhou26** [comment]
How about live streaming?

**Comment by TangZhiZhen** [comment]
For live streaming, pull request is https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/35

**Comment by TangZhiZhen** [comment]
https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/35 has been merged
