### ISSUE TITLE
starting live transcore docker

### ISSUE THREAD

**Issue by khadija2111** [OpenVisualCloud/CDN-Transcode-Sample#112]
when i try to create the live transcode docker instance, the terminal signals an error: 
"Unable to find image 'ovc_transcode_service:latest' locally"

1. Go to manual deploy
2. Click on "Start live transcode docker"
3. on the terminal, run the command: "docker run -it --network=my_bridge --ip 192.168.31.32 --name live-transcode-service -v /var/www/dash:/var/www/dash -v /var/www/hls:/var/www/hls ovc_transcode_service /bin/bash"

what is expected is the container ID created

**Comment by TangZhiZhen** [comment]
@khadija2111 Did you build the xcode-server under CDN_Transcode_Sample?

Build
On CDN-Transcode Server, run below command to build docker images:

mkdir build
cd build
cmake ..
make

**Comment by khadija2111** [comment]
I did what you recommended me but i have the same problem..

**Comment by chuan12x** [comment]
1.What is your system version?
2.You can find the image after cdn make, use command like this: 
      docker images -a | grep ovc_transcode_service
my result is:
ovc_transcode_service                latest              6f7edf8b4137        12 days ago         387MB
ovc_transcode_service                build               362762b458a8        12 days ago         4.57GB

**Comment by chuan12x** [comment]
1.What is your system version?
2.You can find the image after cdn make, use command like this:
docker images -a | grep ovc_transcode_service
my result is:
ovc_transcode_service latest 6f7edf8b4137 12 days ago 387MB
ovc_transcode_service build 362762b458a8 12 days ago 4.57GB

**Comment by khadija2111** [comment]
actually my result is:
Unable to find image 'ovc_transcode_service:latest' locally
docker: Error response from daemon: pull access denied for ovc_transcode_service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
maybe the problem is that the access to the resource is denied?

**Comment by chuan12x** [comment]
@khadija2111 
1.The sample can only run on Ubuntu 18.04/CentOS 7.6, what is your system version?

**Comment by khadija2111** [comment]
oh you are right i don't have the good version unfortunately (i have ubuntu 18.04.3 LTS)

**Comment by chuan12x** [comment]
system version error.
