### ISSUE TITLE
HTTP upload support for VOD

### ISSUE THREAD

**Issue by czhou26** [OpenVisualCloud/CDN-Transcode-Sample#12]
Upload UGC video clip via HTTP and then do offline transcode in HLS & DASH format

**Comment by TangZhiZhen** [comment]
will use nginx-upload module to support this feature.

**Comment by TangZhiZhen** [comment]
assgin to mingwu123123

**Comment by mingwu123123** [comment]
https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/61
