### ISSUE TITLE
CDN code compile failed  while run "make volume"  since this commit "42b45bba"

### ISSUE THREAD

**Issue by meiyanz** [OpenVisualCloud/CDN-Transcode-Sample#154]
**Issue Description:**
CDN code stuck on compile failure  "make volume"  since this commit "42b45bba"
**Error log:**
root@media-server-zhangchuang-2:build#make volume
Scanning dependencies of target volume
Making volumes...
awk: line 18: syntax error at or near [
awk: line 19: syntax error at or near [
awk: line 23: syntax error at or near [
awk: line 25: syntax error at or near [
awk: line 28: syntax error at or near }
deployment/kubernetes/CMakeFiles/volume.dir/build.make:57: recipe for target 'deployment/kubernetes/CMakeFiles/volume' failed
make[3]: *** [deployment/kubernetes/CMakeFiles/volume] Error 2
CMakeFiles/Makefile2:328: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/all' failed
make[2]: *** [deployment/kubernetes/CMakeFiles/volume.dir/all] Error 2
CMakeFiles/Makefile2:335: recipe for target 'deployment/kubernetes/CMakeFiles/volume.dir/rule' failed
make[1]: *** [deployment/kubernetes/CMakeFiles/volume.dir/rule] Error 2
Makefile:183: recipe for target 'volume' failed
make: *** [volume] Error 2
**Reproduce Rate: 100%.**
**Command** : make volume
**The commit information:**  commit 42b45bbad44c4d53f8686ff60e4c0462fe49a003

**Comment by xwu2git** [comment]
I could not reproduce. Does it work for you on the latest master? There are multiple commits after this one.

**Comment by meiyanz** [comment]
Hi @xwu2git 
yes, the latest master has this issue either.
Reproduce:
$ git clone https://github.com/OpenVisualCloud/CDN-Transcode-Sample.git
$ cd CDN-Transcode-Sample
$ sudo -E ./script/install_dependency.sh
$ sudo mkdir -p /etc/systemd/system/docker.service.d
$ printf "[Service]\nEnvironment=\"HTTPS_PROXY=$https_proxy\" \"NO_PROXY=$no_proxy\"\n" | sudo tee /etc/systemd/system/docker.service.d/proxy.conf
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
$ mkdir build && cd build
$ cmake ..
$ make
$ make volume

**Comment by xwu2git** [comment]
Unable to reproduce. I tested on both Ubuntu1804 and CentOS76. 
Can you attach deployment/kubernetes/*-pv.yaml?

**Comment by meiyanz** [comment]
`video-archive-pv.yaml
apiVersion: storage.k8s.io/v1
  3 kind: StorageClass
  4 metadata:
  5   name: video-archive
  6 provisioner: kubernetes.io/no-provisioner
  7 volumeBindingMode: WaitForFirstConsumer
  8
  9 ---
 10
 11 apiVersion: v1
 12 kind: PersistentVolume
 13 metadata:
 14   name: video-archive
 15 spec:
 16   capacity:
 17     storage: 2Gi
 18   accessModes:
 19   - ReadWriteMany
 20   persistentVolumeReclaimPolicy: Retain
 21   storageClassName: video-archive
 22   local:
 23     path: /tmp/archive/video
 24   nodeAffinity:
 25     required:
 26       nodeSelectorTerms:
 27       - matchExpressions:
 28         - key: kubernetes.io/hostname
 29           operator: In
 30           values:
 31           - "media-server-zhangchuang-2"`

**Comment by xwu2git** [comment]
No issue in the PV file. The host is correctly detected. 
BTW, do you have 'awk' installed on your system?

**Comment by meiyanz** [comment]
@xwu2git ,
would you  mind show me how to compile? 
my server :10.67.112.159 
user: media
password: intel123
code path: /home/media/wookroom/0602-2/CDN-Transcode-Sample

**Comment by meiyanz** [comment]
'awk ' runs well:
root@media-server-zhangchuang-2:kubernetes#ls | awk '{print $1}'
build.sh
cdn-deploy.yaml
cdn-svc.yaml
CMakeCache.txt
CMakeFiles
CMakeLists.txt
cpu_mem_management.cfg
helm
kafka-deploy.yaml
kafka-svc.yaml
live-0-deploy.yaml
live-transcode.cfg
logging
mkvolume.sh
monitoring
__pycache__
redis-deploy.yaml
redis-svc.yaml
video-archive-pvc.yaml
video-archive-pv.yaml
video-archive-pv.yaml.m4
video-cache-pvc.yaml
video-cache-pv.yaml
video-cache-pv.yaml.m4
volume-info.sh
yaml
zookeeper-deploy.yaml
zookeeper-svc.yaml

**Comment by xwu2git** [comment]
You did not have kubernetes installed on your system. 
make volume is specific to Kubernetes.
If you just want to run docker swarm, run it without 'make volume'.

**Comment by meiyanz** [comment]
The  Kubernetes  is installed on this server,  run "make volume" still error just list before.

**Comment by xwu2git** [comment]
$ kubectl get node
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

**Comment by xwu2git** [comment]
Please make sure Kubernetes is working.

**Comment by meiyanz** [comment]
yes, kubernates is working: 
root@media-server-zhangchuang-2:script#kubectl get nodes
NAME                         STATUS   ROLES    AGE   VERSION
media-server-zhangchuang-2   Ready    master   18h   v1.18.2

**Comment by yinggux** [comment]
> awk

@meiyanz according to reply, "make volume" work well after install awk(apt-get install gawk)

**Comment by xwu2git** [comment]
Do you have another version of awk on the system before?

**Comment by meiyanz** [comment]
see one:
root@media-server-zhangchuang-2:CDN-Transcode-Sample#gawk --version
GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)
Copyright (C) 1989, 1991-2016 Free Software Foundation.
