### ISSUE TITLE
CDN Transcode deploy failed

### ISSUE THREAD

**Issue by meiyanz** [OpenVisualCloud/CDN-Transcode-Sample#156]
**Issue Description**:
CDN code failed while deploy "make start_kubernetes" 
**Error log**:
deployment.apps/vod created
deployment.apps/kafka created
error: no objects passed to apply
deployment/kubernetes/yaml/CMakeFiles/start_kubernetes.dir/build.make:57: recipe for target 'deployment/kubernetes/yaml/CMakeFiles/start_kubernetes' failed
make[3]: *** [deployment/kubernetes/yaml/CMakeFiles/start_kubernetes] Error 1
CMakeFiles/Makefile2:570: recipe for target 'deployment/kubernetes/yaml/CMakeFiles/start_kubernetes.dir/all' failed
make[2]: *** [deployment/kubernetes/yaml/CMakeFiles/start_kubernetes.dir/all] Error 2
CMakeFiles/Makefile2:577: recipe for target 'deployment/kubernetes/yaml/CMakeFiles/start_kubernetes.dir/rule' failed
make[1]: *** [deployment/kubernetes/yaml/CMakeFiles/start_kubernetes.dir/rule] Error 2
Makefile:261: recipe for target 'start_kubernetes' failed
make: *** [start_kubernetes] Error 2
make: *** [volume] Error 2
**Reproduce Rate**: 100%.
**failed Command** : make start_kubernetes
**The commit information**: commit 9146a6576415e3e367075098bf9c4ab9e29f61ba
**Reproduce**:
$ git clone https://github.com/OpenVisualCloud/CDN-Transcode-Sample.git
$ cd CDN-Transcode-Sample
$ sudo -E ./script/install_dependency.sh
$ sudo mkdir -p /etc/systemd/system/docker.service.d
$ printf "[Service]\nEnvironment="HTTPS_PROXY=$https_proxy" "NO_PROXY=$no_proxy"\n" | sudo tee /etc/systemd/system/docker.service.d/proxy.conf
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
$ mkdir build && cd build
$  cmake ../ -DNVODS=1 -DNLIVES=0
$ make
$ make volume
$ cd ../
$ mkdir -p /etc/systemd/system/kubelet.service.d/
$ printf "[Service]\nEnvironment=\"HTTPS_PROXY=$https_proxy\" \"NO_PROXY=$no_proxy\"\n" | sudo tee /etc/systemd/system/kubelet.service.d/proxy.conf
$ ./script/Kubernetes_setup_master.sh 
$ kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') | grep token: | awk '{print $2}'
$ make start_kubernetes

**Comment by xwu2git** [comment]
Fixed in #157

**Comment by meiyanz** [comment]
thanks， VOD works now, this issue fixed！
