### ISSUE TITLE
batch-5n4c9 pod pull image error

### ISSUE THREAD

**Issue by igustas** [OpenVisualCloud/CDN-Transcode-Sample#173]
Issue Description:
batch-5n4c9 pod pull image error.

Error log:
# kubectl describe pods batch-5n4c9
..........................
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedScheduling 7m2s default-scheduler persistentvolumeclaim "video-archive" not found
Warning FailedScheduling 7m2s default-scheduler persistentvolumeclaim "video-archive" not found
Normal Scheduled 6m59s default-scheduler Successfully assigned default/batch-5n4c9 to av09-15-wp
Normal AddedInterface 6m57s multus Add eth0 [10.244.1.20/24]
Normal Pulling 5m8s (x4 over 6m57s) kubelet Pulling image "tc_batch_service:latest"
Warning Failed 5m3s (x4 over 6m45s) kubelet Failed to pull image "tc_batch_service:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for tc_batch_service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Warning Failed 5m3s (x4 over 6m45s) kubelet Error: ErrImagePull
Normal BackOff 4m38s (x7 over 6m45s) kubelet Back-off pulling image "tc_batch_service:latest"
Warning Failed 110s (x19 over 6m45s) kubelet Error: ImagePullBackOff

Reproduce Rate: 100%.

The commit information: commit 8161137975fd18ef2a4edf134bc23b29c6adc1b1

tc_batch_service:latest image is not built

**Comment by lvcarry** [comment]
Add more info:
**Test commit:** 97aa07fec20268591827f6116366c2d503456158
**Analyze:**
It’s OK on “cdn transcode” scenario. But it’s failed to run one pod “tc_batch_service” on “cdn” scenario.
It seems this image is for cdn xcode only but deployments will pull it even on cdn case.
