### ISSUE TITLE
CDN building image is stuck

### ISSUE THREAD

**Issue by igustas** [OpenVisualCloud/CDN-Transcode-Sample#187]
Issue Description:
CDN building image is stuck.

Reproduce Rate: 100%.

error：
commits id : 4e7f204fc6e08b35ab0f716a5dd98c6003faf09a
When installing CDN, it will support stuck in the build process. This problem occurs on both ubuntu18.04 and centos7.6

**Comment by QuPengfei** [comment]
would you share the error info?  i can build the image successfully on Centos7.6. not yet try  on ubuntu.

**Comment by igustas** [comment]
"cmd": "/usr/bin/make", "msg": "\"docker build\" requires exactly 1 argument.\nSee 'docker build --help'.\n\nUsage:  docker build [OPTIONS] PATH | URL | -\n\nBuild an image from a Dockerfile\nmake[2]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate] Error 1\nmake[1]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/all] Error 2\nmake: *** [all] Error 2", "rc": 2, "stderr": "\"docker build\" requires exactly 1 argument.\nSee 'docker build --help'.\n\nUsage:  docker build [OPTIONS] PATH | URL | -\n\nBuild an image from a Dockerfile\nmake[2]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate] Error 1\nmake[1]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/all] Error 2\nmake: *** [all] Error 2\n", "stderr_lines": ["\"docker build\" requires exactly 1 argument.", "See 'docker build --help'.", "", "Usage:  docker build [OPTIONS] PATH | URL | -", "", "Build an image from a Dockerfile", "make[2]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate] Error 1", "make[1]: *** [deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/all] Error 2", "make: *** [all] Error 2"], "stdout": "deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/build.make:57: recipe for target 'deployment/certificate/CMakeFiles/build_ovc_self_certificate' failed\nCMakeFiles/Makefile2:142: recipe for target 'deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/all' failed\nMakefile:83: recipe for target 'all' failed\n", "stdout_lines": ["deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/build.make:57: recipe for target 'deployment/certificate/CMakeFiles/build_ovc_self_certificate' failed", "CMakeFiles/Makefile2:142: recipe for target 'deployment/certificate/CMakeFiles/build_ovc_self_certificate.dir/all' failed", "Makefile:83: recipe for target 'all' failed"]

**Comment by lvcarry** [comment]
sorry, we found it's CIR script issue. Close it.
