### ISSUE TITLE
Output stream only have one Representation (one video) in AdaptationSet of DASH if use ffmpeg rtmp sending the Xcode stream to Nignix server for Dash segment. 

### ISSUE THREAD

**Issue by wangjingz** [OpenVisualCloud/CDN-Transcode-Sample#19]
**Describe the bug**
Output stream of CDN-Transcoding sample only have one Representation (one video) in AdaptationSet of DASH if use ffmpeg rtmp sending the stream to Nginx server for Dash segment. 

**To Reproduce**
1. complete 1toN transcoding with Nignx docker setup according to readme. 
start 1: xeon-ubuntu1804-ffmpeg:1.0 docker to complete transcoding task. 
start 2: xeon-ubuntu1804-nginx-rtmp:1.0 docker to complete Dash segment. 

2. input streaming as:
root@f1ac23ac6f74:/media/_System_Validation# ffmpeg -re -i /media/_System_Validation/mp4_h264aac/h264_1920x1080_b@40_2397_8225kbps_cbr_aac_lc_256kbps_48000_hd_the_living_see_2mn48s.mp4 -c:v copy -f flv rtmp://192.168.31.32/stream/xcode

3. Xcode server to do transcoding and rtmp upstreaming to nginx server:
transcoding (xeon-ubuntu1804-ffmpeg:1.0 docker) -> DASH segement MPD file (xeon-ubuntu1804-nginx-rtmp:1.0 docker )
command as: 
ffmpeg -i rtmp://192.168.31.32/stream/xcode -c:a copy -c:v libsvt_hevc -f flv rtmp://192.168.31.31/dash/hevc

4. only have one video in MPD file. (xeon-ubuntu1804-nginx-rtmp:1.0 docker )
only one stream is supported in flv format. 

**Expected behavior**
 need multi-video in DASH MPD with different resolution and bitrate to adapt different network situation.  
**Additional context**
just link use ffmpeg command line to achieve multi-video : 
```bash
root@1fb8d4cd2580:/media/dash# ffmpeg -i rtmp://192.168.31.32/stream/xcode -filter_complex 'split=2[s0][s1];[s0]scale=480:-2[480s];[s1]scale=1080:-2[1080s]' -map '[480s]' -c:v:0 libsvt_hevc -map '[1080s]' -c:v:1 libsvt_hevc -map a -c:a:0 copy -ar:a:0 22050 -map a -c:a:1 copy -ar:a:1 44100 -g 150 -sc_threshold 0 -b_strategy 0 -min_seg_duration 5000 -use_timeline 0 -use_template 1 -single_file 1 -window_size 5 -adaptation_sets "id=0,streams=v id=1,streams=a" -f dash /media/dash/hevc_audiocopy.mpd 
```

**Comment by TangZhiZhen** [comment]
this issue is duplicated with https://github.com/OpenVisualCloud/CDN-Transcode-Sample/issues/10
the #26 is merged and close this issue
