### ISSUE TITLE
Feature request to integrate with Kubernetes

### ISSUE THREAD

**Issue by czhou26** [OpenVisualCloud/CDN-Transcode-Sample#2]

**Comment by TangZhiZhen** [comment]
Done. https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/40

**Comment by TangZhiZhen** [comment]
You can follow the wiki https://github.com/OpenVisualCloud/CDN-Transcode-Sample/wiki/CDN-Transcode-Sample-Getting-Started-Guide to setup kubernetes deploy environment.
