### ISSUE TITLE
Error "av_interleaved_write_frame(): Broken pipe" occurred and make transcoding app exit when do transcoding with DASH/HLS/RTMP

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/CDN-Transcode-Sample#30]
**Describe the bug**
While use such user case "1 xcode + 1 cdn docker + 1 4k streaming output + Dash/HLS/RTMP" to do transcoding, error "av_interleaved_write_frame(): Broken pipe" is printed after do transcoding about 40 frames, transcoding app FFMPEG exit.

Try several different combinations, the detail result as below table:

Input | Transcode +   Output | Result
-- | -- | --
Local | Xcode + Local | Pass
Local | Xcode + CDN DASH   Streaming | Fail
Host Streaming | Xcode + CDN DASH   Streaming | Fail
Host Streaming | Host + Host local | Pass
Host Streaming | Host + Host DASH   Streaming | Pass (libx264)
CDN Server   Streaming | Host + Host DASH   Streaming | Pass (libx264)
CDN Server   Streaming | Host + CDN DASH   Streaming | Fail (libx264)
CDN Server   Streaming | Xcode + Local | Fail on other known   issue
CDN Server   Streaming | Xcode + CDN DASH   Streaming | Fail (libx264 &   svt-hevc)

**To Reproduce**
1. Streaming input in one cdn server: ffmpeg -re -stream_loop -1 -i input_clip_name -c:v copy -c:a copy -f flv rtmp://nginx_ip_1:port_ID_1/stream/nature
2. Run transcoding command in xcode server: ffmpeg -i rtmp://nginx_ip_1:port_ID_1/stream/nature -s 4096x2160 -c:a copy -c:v libsvt_hevc  -f flv rtmp://nginx_ip_2:port_ID_2/dash/4kCamera

**Comment by TangZhiZhen** [comment]
it looks like ffmpeg vaapi issue, will submit issue into ffmpeg.

**Comment by chuchenyan** [comment]
> it looks like ffmpeg vaapi issue, will submit issue into ffmpeg.

@TangZhiZhen ,what's the status?

**Comment by xinglongx** [comment]
can't reproduce this issue in the lastest code.
commit id: 9512773a1091dade41a9271f0a4b24182a1044d9
streaming server: ffmpeg -re -stream_loop -1 -i *.mp4 -c:v copy -c:a copy -f flv rtmp://streaming_IP/myapp/test
live transcode server: ffmpeg -i rtmp://streaming_IP/myapp/test -s 4096x2160 -c:a copy -c:v libsvt_hevc -f flv rtmp://cdn-service/dash/4k
![transcode](https://user-images.githubusercontent.com/51697910/59318028-2dd19a00-8cf8-11e9-80d3-79c8e2137e0f.JPG)
