### ISSUE TITLE
ffplay and VLC can't play x265 clips with HTTP which is generated in xcode server

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/CDN-Transcode-Sample#33]
**Describe the bug**
Using 1 xcode server + 1 cdn server to do H264/MPEG2 transcoding to x265, the transcoding is ok and the output file index.m3u8 or index.mpd is also generated with normal size, but while using ffplay or VLC to play the x265 clips with HLS or DASH, there will be no output in screen and error log is printed by ffplay.

**Command line and Log information from FFPLAY:**
command: 
ffplay http://host_ip:port_id/hls/4kCamera/index.m3u8
Log:
ffplay version 4.1 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration:
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
[hls,applehttp @ 0x7f803c000b80] Opening 'http://host_ip:port_id/hls/4kCamera/0.ts' for reading
[NULL @ 0x7f803c025dc0] PPS id out of range: 0
[hevc @ 0x7f803c027a00] PPS id out of range: 0
[hevc @ 0x7f803c027a00] Error parsing NAL unit #1.
[NULL @ 0x7f803c025dc0] PPS id out of range: 0
[hevc @ 0x7f803c027a00] PPS id out of range: 0
[hevc @ 0x7f803c027a00] Error parsing NAL unit #1.
[NULL @ 0x7f803c025dc0] PPS id out of range: 0
[hevc @ 0x7f803c027a00] PPS id out of range: 0
[hevc @ 0x7f803c027a00] Error parsing NAL unit #1.
[NULL @ 0x7f803c025dc0] PPS id out of range: 0
[hevc @ 0x7f803c027a00] PPS id out of range: 0
[hevc @ 0x7f803c027a00] Error parsing NAL unit #1.
[NULL @ 0x7f803c025dc0] PPS id out of range: 0
[hevc @ 0x7f803c027a00] PPS id out of range: 0

**NOTE:**  If streaming output x265 stream with RTMP during transcoding, then use ffplay to playback with RTMP, the output is ok but has about 15s delay; If play with VLC also no output in screen.

**To Reproduce**
1. Run transcode command in xcode server: ffmpeg -re -stream_loop -1 -i  /var/www/Mpeg2_1080.m2v  -c:v libx265 -s 4096x2160 -f flv rtmp://ngnix_id:port_id/hls/4kCamera
2. Run ffplay (with HEVC enabled patch) command in another Linux machine: 
ffplay http://host_ip:port_id/hls/4kCamera/index.m3u8 or play with VLC on your windows PC.

**Expected behavior**
Video should be played smoothly with FFPLAY or VLC, no error and no delay.

**Comment by TangZhiZhen** [comment]
won't support x265 rtmp in transcoder, as current FFmpeg based transcode is sufficient to showcase the CDN transcode pipeline
