### ISSUE TITLE
CDN-Transcode-Sample get fail info and exit after do transcoding to SVT-HEVC about 90 frames when set 3 streaming output as 4k with RTMP/HLS/DASH

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/CDN-Transcode-Sample#34]
**Describe the bug**
Live streaming with 1 xcode + 1 cdn docker and do transcoding to SVT-HEVC, then config 3 streaming output as 4k resolution with RTMP or HLS or DASH, the xcode Sample (ffmpeg) will get fail info and exit after transcoding about 90 frames.
In our side, the issue has about 80% reproducing rate.
The detail fail info in xcode server as below:
[flv @ 0x55b8be882440] Failed to update header with correct duration.
[flv @ 0x55b8be882440] Failed to update header with correct filesize.
[flv @ 0x55b8be881640] Failed to update header with correct duration.
[flv @ 0x55b8be881640] Failed to update header with correct filesize.
[flv @ 0x55b8be8f4480] Failed to update header with correct duration.
[flv @ 0x55b8be8f4480] Failed to update header with correct filesize.
frame=  152 fps=9.7 q=-0.0 Lq=-0.0 q=-0.0 size=     686kB time=00:00:04.77 bitrate=1178.0kbits/s speed=0.305x
video:1988kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**NOTE:** This issue may be blocked by known issue #30.

**To Reproduce**
1. Streaming input in one cdn server: ffmpeg -re -stream_loop -1 -i _input_clip_name_ -c:v copy -c:a copy -f flv rtmp://ngnix_ip1:port_id1/stream/nature
2. Run transcoding command in xcode server: ffmpeg -i rtmp://ngnix_ip1:port_id1/stream/nature -s 4096x2160 -c:a copy -c:v libsvt_hevc  -f flv rtmp://ngnix_ip2:port_id2/hls/4kCamera -s  4096x2160 -c:a copy -c:v libsvt_hevc -f flv rtmp://ngnix_ip2:port_id2/hls/4kCamera_1 -s 4096x2160 -c:a copy -c:v libsvt_hevc -f flv rtmp://ngnix_ip2:port_id2/hls/4kCamera_2

**Expected behavior**
Transcoding should be no error, no hang, and the output video should be play in normal.

**Comment by TangZhiZhen** [comment]
it looks like svt-hevc issue,  will submit issue into svt-hevc

**Comment by chuchenyan** [comment]
@TangZhiZhen , what's the status?

**Comment by xinglongx** [comment]
can't reproduce this issue by lastest code 
transcoding without any error till 1000 frames
![hls](https://user-images.githubusercontent.com/51697910/59256210-0cc06900-8c66-11e9-82be-12a6453c6a4a.JPG)
