### ISSUE TITLE
Feature request to support HTTP-FLV

### ISSUE THREAD

**Issue by czhou26** [OpenVisualCloud/CDN-Transcode-Sample#9]
Use HTTP-FLV to delivery live stream in flv format over HTTP, which could traverse firewall and meanwhile provide lower latency than DASH/HLS. It's a very common in China.

**Comment by TangZhiZhen** [comment]
My understanding is that enable HTTP-FLV support on live streaming mode. because HTTP-FLV is more widely used in the field of live broadcasting.

**Comment by czhou26** [comment]
HTTP-FLV is for live streaming, not for VOD.

**Comment by czhou26** [comment]
Will use nginx-http-flv module to support this feature.

**Comment by TangZhiZhen** [comment]
Done. https://github.com/OpenVisualCloud/CDN-Transcode-Sample/pull/65
